version: '3.2'
services:
  dev-image:
    image: mycppdev
    build:
      context: .
    ports:
      - "2000:2000"
    privileged: true
    container_name: devenv
# mapping your project folder (.) to /home/develop/project    
    volumes:
      - "./:/src"
      
